services:
  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py:ro
      - ./loco.sqlite:/my-app/loco.sqlite
    environment:
      - SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
